version: '3.8'

services:
    scylla:
        image: scylladb/scylla:5.4.1 # Using a specific version is good practice
        container_name: some-scylla
        ports:
            - "9042:9042"
        # FIX: Added broadcast address for stable local connections
        command: --smp 1 --memory 1G --broadcast-rpc-address 127.0.0.1
        networks:
            - rental-net
        volumes:
            - scylla_data:/var/lib/scylla # Persist data

    rental-api:
        build: .
        container_name: rental-api
        ports:
            - "8080:8080"
        depends_on:
            - scylla
        networks:
            - rental-net
        environment:
            - server.servlet.context-path=/api/v1
            - server.error.include-message=always
            - server.error.include-binding-errors=always

            # FIX: Corrected Cassandra properties for Spring Boot 3.x
            - SPRING_DATA_CASSANDRA_CONTACT_POINTS=scylla
            - SPRING_DATA_CASSANDRA_KEYSPACE_NAME=rental
            # - SPRING_DATA_CASSANDRA_USERNAME=cassandra # Default Scylla image has no auth
            # - SPRING_DATA_CASSANDRA_PASSWORD=cassandra # Default Scylla image has no auth
            - SPRING_DATA_CASSANDRA_PORT=9042 # Correct port
            - SPRING_DATA_CASSANDRA_LOCAL_DATACENTER=datacenter1
            - spring.data.cassandra.schema-action=CREATE_IF_NOT_EXISTS
            - spring.data.cassandra.request.timeout=10s
            - spring.data.cassandra.connection.connect-timeout=10s
            - spring.data.cassandra.connection.init-query-timeout=10s

            # config cors (these are also in application.properties, env vars will override)
            - app.cors.allowed-origins=http://localhost:3000,http://localhost:8080,http://localhost:4200
            - app.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS,PATCH
            - app.cors.allowed-headers=*
            - app.cors.allow-credentials=true

            #config jwt
            - app.jwt.secret=KsBman55FbHOoyT2SCZl46RZnc0oySFlenms644lQPKOt//JW78D5brRZuWelLzVts/ACnJcdXtIEl3D57KO5w==
            - app.jwt.expiration=86400000
            - app.jwt.refresh-expiration=604800000

            # config swagger
            - springdoc.api-docs.path=/v3/api-docs
            - springdoc.swagger-ui.path=/swagger-ui.html

            # config file
            - app.file.upload-dir=/app/uploads # Use the path inside the container

networks:
    rental-net:
        driver: bridge

volumes:
    scylla_data: