version: '3.8'

services:
    scylla:
        image: scylladb/scylla
        container_name: some-scylla
        ports:
            - "9042:9042"
        networks:
            - scylla-net

    rental-api:
        build: .
        container_name: rental-api
        ports:
            - "8080:8080"
        depends_on:
            - scylla
        networks:
            - scylla-net
        environment:
            - server.servlet.context-path=/api/v1
            - server.error.include-message=always
            - server.error.include-binding-errors=always

            # config cassandra
            - SPRING_CASSANDRA_CONTACT_POINTS=scylla
            - SPRING_CASSANDRA_KEYSPACE_NAME=rental
            - SPRING_CASSANDRA_USERNAME=cassandra
            - SPRING_CASSANDRA_PASSWORD=cassandra
            - SPRING_CASSANDRA_PORT=9045
            - SPRING_CASSANDRA_LOCAL_DATACENTER=datacenter1
            - spring.cassandra.schema-action=CREATE_IF_NOT_EXISTS
            - spring.cassandra.request.timeout=10s
            - spring.cassandra.connection.connect-timeout=10s
            - spring.cassandra.connection.init-query-timeout=10s

            # config cors
            - app.cors.allowed-origins=http://localhost:3000,http://localhost:8080,http://localhost:4200
            - app.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS,PATCH
            - app.cors.allowed-headers=*
            - app.cors.allow-credentials=true

            #config jwt
            - app.jwt.secret=KsBman55FbHOoyT2SCZl46RZnc0oySFlenms644lQPKOt//JW78D5brRZuWelLzVts/ACnJcdXtIEl3D57KO5w==
            - app.jwt.expiration=86400000
            - app.jwt.refresh-expiration=604800000

            # config swagger
            - springdoc.api-docs.enabled=true
            - springdoc.api-docs.path=/v3/api-docs
            - springdoc.swagger-ui.enabled=true
            - springdoc.swagger-ui.path=/swagger-ui.html
            - springdoc.swagger-ui.operations-sorter=method
            - springdoc.swagger-ui.tags-sorter=alpha
            - springdoc.swagger-ui.display-request-duration=true
            - springdoc.swagger-ui.show-extensions=true
            - springdoc.swagger-ui.show-common-extensions=true

            # config file
            - spring.servlet.multipart.enabled=true
            - spring.servlet.multipart.max-file-size=10MB
            - spring.servlet.multipart.max-request-size=10MB
            - app.file.upload-dir=./uploads
            - app.file.max-file-size=10485760
            - app.file.allowed-extensions=jpg,jpeg,png,pdf,doc,docx

networks:
    scylla-net:
        driver: bridge
